### ISSUE TITLE
WEB界面美化等功能建议

### ISSUE THREAD

**Issue by goodfortuneqi** [djylb/nps#1]
首先感谢作者听取了建议，更新了功能，
建议开个群，方便交流，
还有就是建议这个界面美工再优化一下，目前感觉不太好看，或者恢复成原始那样，（笑脸）
FRP有远程管理功能，建议NPS也可以增加，
目前存在一个BUG，用NPS restart 重启NPS后，马上进后台看，会发现有一些客户端上线，多NPS restart 几次又好了，

**Comment by 30873732** [comment]
web界面加个夜间模式会好点

**Comment by 30873732** [comment]
白色太亮了

**Comment by djylb** [comment]
关于页面风格想用原来的直接把web/static/css/style.css换成旧的就行，不过界面排版就是个问题了。
另外我不是专门搞前端开发的，要是有人愿意美化页面的话欢迎提PR。

**Comment by djylb** [comment]
https://github.com/djylb/nps/blob/master/web/static/css/style-old.css

需要旧版风格自行下载上面文件替换web/static/css/style.css文件即可，界面排版按照新style.css可能存在问题，不过不影响使用就是了。

有美观需求的话建议提个PR我合并到下一个版本里。

**Comment by djylb** [comment]
关于前面提到的BUG，建议提供更详细的操作和日志说明，另外不要在一条ISSUE里塞太多内容，BUG和功能建议分开提。

**Comment by djylb** [comment]
"FRP有远程管理功能，建议NPS也可以增加"
上面这个建议用命令行方式启动客户端，直接在Web界面改配置。
不太想让NPC有文件读写功能，这么搞安全性就有大问题了，要考虑服务端不一定可信。
