### ISSUE TITLE
增加用户权限控制功能

### ISSUE THREAD

**Issue by seocgr** [djylb/nps#10]
nps可以开多用户登陆，普通用户可以user登陆，但是存在一个问题就是不大懂的人进去老是乱删，能不能增加个权限控制让普通用户没有删除权限

**Comment by djylb** [comment]
理论上普通用户应该能够管理自己的映射，你指的是乱删什么？

**Comment by seocgr** [comment]
> 理论上普通用户应该能够管理自己的映射，你指的是乱删什么？

没事啦 已经群里讨论过了 我手动改下前端
