### ISSUE TITLE
标签增加TCP 或其它连接中的，辨识

### ISSUE THREAD

**Issue by goodfortuneqi** [djylb/nps#13]
![image](https://github.com/user-attachments/assets/3a56ed98-834e-4013-b144-4cc07e718e4e)

**Comment by goodfortuneqi** [comment]
当客服端正在连接时可以改变颜色，也可以改为，“活动”等字体，非活动又变成绿色

**Comment by djylb** [comment]
看网速位置就能简单判断了，另外网页是静态的不会实时显示当前变化，目前需要手动刷新网页才能看见最新状态。
建立连接就几十毫秒的事，没必要显示，活动状态直接看网速位置就行了，不过只会显示打开页面瞬时客户端的网速就是了
