### ISSUE TITLE
大神求救！连接错误是什么原因？

### ISSUE THREAD

**Issue by xiaohu911** [djylb/nps#19]
隔几天就会出现这种情况，同线路其他NPS和npc也是不定时出现这种情况。提供错误时的报告，服务器和本地都是win系统搭建。本地用的后台模式。

nps 错误报告
2024/11/26 22:26:30.330 [W] [base.go:124]  get connection from client id 2  error the mux has closed
2024/11/26 22:26:35.469 [I] [bridge.go:449]  the client 2 closed
2024/11/26 22:26:39.793 [W] [base.go:124]  get connection from client id 2  error the client 2 is not connect
2024/11/26 22:26:40.800 [I] [bridge.go:291]  clientId 2 connection succeeded, address:112.193.164.X:63395 

npc 错误报告
2024/11/26 22:26:36.820 [E] [client.go:93]  Accept server data error EOF, end this service
2024/11/26 22:26:36.822 [W] [client.go:166]  accpet error,the conn has closed
2024/11/26 22:26:36.822 [I] [npc.go:286]  Client closed! It will be reconnected in five seconds
2024/11/26 22:26:41.823 [I] [npc.go:284]  start vkey:oxzs8sp6lh6h4lpg
2024/11/26 22:26:42.074 [I] [client.go:73]  Successful connection with server 8.218.232.X:8024

**Comment by djylb** [comment]
能自动重连吗？能的话就是网络丢包了，不太影响使用。disconnect_timeout参数用的是默认值60吗？

**Comment by xiaohu911** [comment]
能自动重连，用的60，同时期其他设备都在一个网络环境，但没有掉，有点搞不懂为什么

**Comment by djylb** [comment]
目前的信息看起来应该只是网络波动导致的重连。
