### ISSUE TITLE
请问下，安装问题

### ISSUE THREAD

**Issue by xiaohu911** [djylb/nps#2]
之前用的其他的版本，如何更新到这个版本了

**Comment by djylb** [comment]
备份原来的conf文件夹，下载仓库最新服务端，执行安装命令（参考官方教程）。照着最新的nps.conf补齐配置文件，理论上这步不做应该也不会报错。

手动安装的话，替换旧的nps可执行文件，覆盖web文件夹，conf文件夹里除了nps.conf文件以外都用原来的，nps.conf文件照着新的示例配置改一下。

简而言之必要操作是替换nps可执行文件，替换web文件夹，其他报错了再改。
