### ISSUE TITLE
Proxy Protocol 无法使用

### ISSUE THREAD

**Issue by sansi98h** [djylb/nps#26]
这是nginx的提示，使用frp的Proxy Protocol 可以正常使用

不管是V1、V2还是关闭，均为以下日志

![image](https://github.com/user-attachments/assets/19b0db26-c1aa-4343-bda5-e96ccd5399fd)

这是npc的日志，使用的是docker安装
![image](https://github.com/user-attachments/assets/10bc2195-6261-429c-86a8-82845195be9f)

这是nps的配置

![image](https://github.com/user-attachments/assets/d69895c7-acdc-45f1-826c-d532e1a31590)

**Comment by djylb** [comment]
服务端是最新版吗？

**Comment by sansi98h** [comment]
> 服务端是最新版吗？要是最新版还有问题的话提供一下Nginx配置，没问题的话直接关闭问题就行。

都是最新版的，这是配置
![image](https://github.com/user-attachments/assets/95b82751-bb2d-4b66-939f-7a243dba95be)

我前端为haproxy或者frp，开启Proxy Protocol 可以正常使用

**Comment by djylb** [comment]
我这边用nginx/1.27.1做后端，使用NPS的TCP转发开启Proxy Protocol V1和V2测试都没问题。
测试使用的Nginx配置：
```
server {
	listen 85 proxy_protocol;
	location / {
	    add_header Content-Type text/plain;
	    return 200 "Client IP: $proxy_protocol_addr\n";
	}
}
server {
	listen 86 ssl proxy_protocol;
        ssl_certificate     /etc/ssl/xxx.pem;
        ssl_certificate_key /etc/ssl/xxx.key;
	location / {
	    add_header Content-Type text/plain;
	    return 200 "Client IP: $proxy_protocol_addr\n";
	}
}
```
效果：
![Snipaste_2024-12-02_18-09-02](https://github.com/user-attachments/assets/789d05fb-a727-47ae-8aa6-2a9d97a7580c)

**Comment by djylb** [comment]
对了NPS只支持自身向后端通过Proxy Protocol传递真实IP，不支持其他前置反向代理传入Proxy Protocol，如果前置代理已经传递了Proxy Protocol的话NPS要关掉这个才行。
如果你方便的话抓包看一下头部具体什么情况，或者提供具体NPS和NGINX的组合方式，我这边需要复现这个问题才能修，不过我用上面的配置测试看起来没问题，我更倾向于推测是你的配置问题。

**Comment by sansi98h** [comment]
> 对了NPS只支持自身向后端通过Proxy Protocol传递真实IP，不支持其他前置反向代理传入Proxy Protocol，如果前置代理已经传递了Proxy Protocol的话NPS要关掉这个才行。 如果你方便的话抓包看一下头部具体什么情况，或者提供具体NPS和NGINX的组合方式，我这边需要复现这个问题才能修，不过我用上面的配置测试看起来没问题，我更倾向于推测是你的配置问题。

前段就nps，然后就转发到了nginx，haproxy是我本地局域网，为了兼容Proxy Protocol才加的，我也正在找问题

**Comment by djylb** [comment]
有nginx了应该不需要haproxy才对，不知道是不是nginx版本问题，你可以拿我上面的测试配置试试看能不能返回真实IP。

**Comment by djylb** [comment]
奇怪了，你截图一下NPS网页仪表盘页面的版本号吧
我这边测试了完整配置也是正常的。
Nginx：
```
server {
	listen 8088 proxy_protocol;

	location / {
	    proxy_pass http://172.16.0.6:88;
	    real_ip_recursive on;
	    set_real_ip_from 0.0.0.0/0;
	    real_ip_header proxy_protocol;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```
NPS:
![Snipaste_2024-12-02_19-11-52](https://github.com/user-attachments/assets/5cf7d3ac-1c52-4242-ab96-2971adde14d1)
浏览器测试：
![Snipaste_2024-12-02_19-05-03](https://github.com/user-attachments/assets/b3703922-b242-4d13-b63a-d6f70be07722)

**Comment by sansi98h** [comment]
![image](https://github.com/user-attachments/assets/a2ed59a8-533e-4e71-91ab-c4bed04e0d83)
为什么你有代理到本地选项，我之前是其它版本的nps，我卸载重装试试

**Comment by sansi98h** [comment]
我好像找到问题了，ya压缩加密打开就不行了
![image](https://github.com/user-attachments/assets/ed7e0ef1-f751-4692-8e0d-046d4a592884)

**Comment by djylb** [comment]
OK，用TLS端口连的话就没必要开加密了，下一版我修一下这个。

**Comment by sansi98h** [comment]
这个配置是总配置，无法单独分开，而且，加密或者压缩，任何一个开了好像都不行

**Comment by djylb** [comment]
已修复
