### ISSUE TITLE
web端连接数不会自动清0，只会网上增加。

### ISSUE THREAD

**Issue by Phoenix660** [djylb/nps#28]
**Describe the bug**
![image](https://github.com/user-attachments/assets/562b0322-caaa-4066-bbf5-4e79ff4a34e8)

如图所示。

**To Reproduce**
1. Opening '...'
3. See error

**Expected behavior**

**Screenshots or logs**
Add screenshots or logs to help explain your problem.

**Server (please complete the following information):**
 - OS: [e.g. Centos, Windows]
 - ARCH: [e.g. Amd64, Arm]
 - Tunnel [e.g. TCP, HTTP]
 - Version [e.g. 0.24.0]

**Client (please complete the following information):**
 - OS: [e.g. Centos, Windows]
 - ARCH: [e.g. Amd64, Arm]
 - Tunnel [e.g. TCP, HTTP]
 - Version [e.g. 0.24.0]

**Additional context**

**Comment by djylb** [comment]
我刚测了下TCP连接数显示是正常的。
建立新TCP连接后计数会增加，连接关闭后会减少计数。域名转发和TCP隧道的TCP计数都没问题。
另外仪表盘显示的信息不会自动刷新，需要手动刷新页面才会显示最新状态信息。
不太清楚你指的是存在什么问题，TCP连接关闭后计数是能够正常减少的，要是还存在问题的话详细描述一下。
