### ISSUE TITLE
[BUG] 流量统计问题

### ISSUE THREAD

**Issue by NJcoxx** [djylb/nps#29]
**BUG1：Socks5代理的流量不计入客户端流量(图1、图2)；**
图1（Socks5代理界面）显示跑了7.15MB流量：
![QQ20241218-161516](https://github.com/user-attachments/assets/9a5605b1-a965-42c4-b8bb-fef27a560d5b)
图2（客户端界面）流量显示为0B：
![Socks5CLIENT](https://github.com/user-attachments/assets/d7703625-5e93-4bce-8772-347ca3178064)

**BUG2：HTTP代理的流量只计入客户端流量，HTTP代理界面不显示流量(图3、图4)；**
图3（HTTP代理界面）流量显示为0B：
![QQ20241218-161911](https://github.com/user-attachments/assets/9facddd1-d115-46a3-ae1f-e56396e8d333)
图4（客户端界面）显示跑了28.90MB流量：
![HTTPCLIENT](https://github.com/user-attachments/assets/1a42f9a0-68a7-41a1-96d6-0530dc135f75)

**Server (please complete the following information):**
 - OS: Debian 6.8.12-4
 - ARCH: amd64
 - Tunnel: TCP HTTP\SOCKS5
 - Version: v0.26.32

**Client (please complete the following information):**
 - OS: Windows11 24H2
 - ARCH: amd64
 - Tunnel: TCP HTTP\SOCKS5
 - Version: v0.26.32

**Comment by djylb** [comment]
好的，刚看了下第一个确实存在，不过第二个算不上bug，目前只设计了一个根据客户端汇总统计流量。
有空我修一下，后期可能会重写流量统计部分。

**Comment by djylb** [comment]
临时修了，socks5流量直接计入客户端了，原始代码这块处理问题不小，回头我彻底重新写一下吧。#30
