### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by xiaohu911** [djylb/nps#4]
大神谢谢你的重装教程，还有一个疑问，替换了主程序以后更新是否就是你的版本了，不会定向到另一个版本吧？

**Comment by djylb** [comment]
目前update是指向当前仓库，不过只替换nps或者npc的话，nps-update或npc-update文件还是旧的，需要复制一份nps或者npc重命名成nps-update或npc-update再执行更新命令。或者重新运行一遍安装指令也会自动替换nps-update或npc-update。
执行更新的时候控制台会输出仓库地址，可以根据输出来判断是否起作用。另外执行update是更新nps-update或npc-update文件所在目录下的nps或者npc文件，最好还是重新运行一下安装命令。

**Comment by xiaohu911** [comment]
好的，明白了，谢谢
