### ISSUE TITLE
能否加一个一键清零流量统计的功能

### ISSUE THREAD

**Issue by EchoMillr** [djylb/nps#5]
能否加一个一键清零流量统计的功能

**Comment by djylb** [comment]
可以考虑，急需的话建议自行修改代码后提个PR

**Comment by djylb** [comment]
![Snipaste_2024-11-22_14-53-28](https://github.com/user-attachments/assets/b192bb93-0af6-4984-bf3f-dce7245a4ce5)
已添加

**Comment by EchoMillr** [comment]
能不能改成全局一件清零🤣🤣🤣，单个的话客户端太多操作起来还是比较麻烦，可以在首页某个位置加

**Comment by djylb** [comment]
先这样，全局回头再说

**Comment by EchoMillr** [comment]
好滴
