### ISSUE TITLE
当打开USER登录后台时，仪表盘不因该显示

### ISSUE THREAD

**Issue by goodfortuneqi** [djylb/nps#7]
![新建 BMP 图像](https://github.com/user-attachments/assets/c17e9e56-4a3e-40ab-bd15-281ddb5d8c8a)

**Comment by djylb** [comment]
感觉不显示仪表盘这个选项就行，多用户这块代码耦合性比较高，有空我倒是可以改改，不过不要有太大期待，这个项目是业余时间维护的，功能性更新没太大动力去搞，不过要是提个PR的话我会去合并的。

**Comment by djylb** [comment]
已修复
